Update README with deployment instructions and steps to integrate minio with jmeter k8s jobs
k8-proxy/p-k8-jmeter-test-engine pull request #35
Opened 2020-10-06 10:07 UTC by pranaysahith

2020-10-06 10:34 UTC, NadHodeGW requested changes
Please add missing command for Prometheus

2020-10-06 10:34 UTC, NadHodeGW commented on kubernetes/common_resources/README.md
>  Connect to Prometheus server on http://localhost:9090 URL by running these commands:
Missing command for Prometheus

2020-10-06 16:47 UTC, pranaysahith commented on kubernetes/common_resources/README.md
>  Connect to Prometheus server on http://localhost:9090 URL by running these commands:
The commands are already there. you are just not able to see in the git difference.

2020-10-07 15:14 UTC, dpatel7 approved these changes

2020-10-07 15:28 UTC, NadHodeGW approved these changes

2020-10-07 15:28 UTC, merged